[env:rp2040_mini]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico 
framework = arduino
board_build.core = earlephilhower

monitor_speed = 115200

; CRITICAL: Use the Adafruit TinyUSB stack
build_flags = -DUSE_TINYUSB

lib_deps = 
    z3t0/IRremote @ ^4.4.1
    adafruit/Adafruit NeoPixel @ ^1.12.0
    adafruit/Adafruit TinyUSB Library @ ^3.3.3